# Colors support set of default names and hex values
#background: "#1e1e2e"
#text: "text"
#accent: "mauve"
#mantle: "mantle"
#crust: "crust"
#overlay0: "overlay0"
#overlay1: "overlay1"
#surface0: "surface0"
#surface1: "surface1"
#normal_mode: "blue"
#insert_mode: "green"
#visual_mode: "mauve"
#comand_mode: "peach"
